In [ ]:
# Day 1
# ----------Numpy

In [2]:
import numpy as np
import pandas as pd

In [ ]:
x1 = [4,8,7,6,9]
str(x1)

'[4, 8, 7, 6, 9]'

In [ ]:
type(x1)

list

In [ ]:
a1 = np.array(x1) # convert array in numpy array
type(a1)

numpy.ndarray

In [ ]:
x1 = [4,8,7,6,9]
a1 = np.array(x1)
type(a1)

numpy.ndarray

In [ ]:
x2 = [6,9,1,3,2]

In [ ]:
a2 = np.array([x1,x2])  # making 2D array
a2

array([[4, 8, 7, 6, 9],
       [6, 9, 1, 3, 2]])

In [ ]:
x1 = list(range(11)) #loop to print 0-10 nums

In [ ]:
x1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a1 = np.arange(11)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a1 = np.arange(3, 14)
a1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
a1 = np.arange(5, 24, 3) # to print in gap (while making list asceneding order there will be -1 at end e.g. 24 is limit so you get 23)
a1

array([ 5,  8, 11, 14, 17, 20, 23])

In [ ]:
a1 = np.arange(5, 24, 4) # to print in gap
a1

array([ 5,  9, 13, 17, 21])

In [ ]:
a1 = np.arange(24, 5, -2) # to print in gap reversed (while making list in descendingg order there will be +1 at end e.g. 5 is limit so you get 6)
a1

array([24, 22, 20, 18, 16, 14, 12, 10,  8,  6])

In [ ]:
a1 = np.linspace(10,30,7) #gap will be decided automatically, it prints from 10 to 30 (start, end, number of values)
a1

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        ])

In [ ]:
a1 = np.linspace(10,30,7, endpoint=False)
a1

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714])

In [ ]:
a1 = np.array([4,8,6,5,9])
np.append(a1,3) #permanently appended

array([4, 8, 6, 5, 9, 3])

In [ ]:
a2 = np.array([2,9,8])


In [ ]:
a3 = np.concatenate((a1,a2)) #concatenation
a3

array([4, 8, 6, 5, 9, 2, 9, 8])

In [ ]:
a2 = np.insert(a1, 2, 1) #inserting in array (array, index, value)
a2

array([4, 8, 1, 6, 5, 9])

In [ ]:
np.delete(a2, 2)

array([4, 8, 6, 5, 9])

In [ ]:
a2 = np.delete(a2, 2)
a2

array([4, 8, 5, 9])

In [ ]:
a1 = np.array([3,2,6,7,8,5,4,6])
len(a1)

8

In [ ]:
a2 = a1.reshape(4,2) #creating multidimentional arayr #first number for row and second number for columns
a2

array([[3, 2],
       [6, 7],
       [8, 5],
       [4, 6]])

In [ ]:
a1 = np.array([3,2,6,7,8,5,4,6,])
len(a1)

8

In [ ]:
a2 = a1.reshape(4,3) #creating MDArray for 9 values is not possible with (4,2) matrix se can
a2

ValueError: cannot reshape array of size 8 into shape (4,3)

In [ ]:
# to count the dimensions just count number of square brackets

In [ ]:
a3 = a1.reshape(-1, 1) #number of rows python will decide and number of coluns should be 1
a3

array([[3],
       [2],
       [6],
       [7],
       [8],
       [5],
       [4],
       [6]])

In [ ]:
a4 = a1.reshape(-1, 2) #number of rows python will decide and number of coluns should be 2       #-1 will leave the rows free
a4

array([[3, 2],
       [6, 7],
       [8, 5],
       [4, 6]])

In [ ]:
a4[2] # to print

array([8, 5])

In [ ]:
a4[2:] # to print the rows

array([[8, 5],
       [4, 6]])

In [ ]:
a4[:, 1] # too print the columns

array([2, 7, 5, 6])

In [ ]:
a4[[2,3],:]

array([[8, 5],
       [4, 6]])

In [ ]:
newcol = np.array([3,1,7,9])

In [ ]:
newcol = newcol.reshape(-1, 1)
newcol

array([[3],
       [1],
       [7],
       [9]])

In [ ]:
a4 = np.hstack([a4,newcol])

In [ ]:
a4

array([[ 3,  2,  4,  3],
       [ 6,  7,  7,  1],
       [ 8,  5,  6,  7],
       [10, 14,  9, 17],
       [ 4,  6,  8,  9],
       [ 1,  2,  1,  3]])

In [ ]:
newrow = np.array([1,2,3])

In [ ]:
a4 = np.vstack([a4,newrow])

In [ ]:
a4

array([[3, 2, 3],
       [6, 7, 1],
       [8, 5, 7],
       [4, 6, 9],
       [1, 2, 3]])

In [ ]:
a4 = np.insert(a4, 3,[10,14,17], axis=0)
a4

array([[ 3,  2,  3],
       [ 6,  7,  1],
       [ 8,  5,  7],
       [10, 14, 17],
       [ 4,  6,  9],
       [ 1,  2,  3]])

In [ ]:
a4 = np.insert(a4, 2,[4,7,6,9,8,1], axis=1) # axis 1 refers too column number which is 2.
a4

array([[ 3,  2,  4,  3],
       [ 6,  7,  7,  1],
       [ 8,  5,  6,  7],
       [10, 14,  9, 17],
       [ 4,  6,  8,  9],
       [ 1,  2,  1,  3]])

In [ ]:
a5 =  np.delete(a4,(1,3),axis=0)
a5

array([[3, 2, 4, 3],
       [8, 5, 6, 7],
       [4, 6, 8, 9],
       [1, 2, 1, 3]])

In [ ]:
# Broadcasting: It makes it possible to repeat samee opertion across all the values

In [ ]:
a1 = np.array([4,7,6,8,9])
a2 = np.array([4,2,7,6,3])

In [ ]:
a3 = a1+5
a3

array([ 9, 12, 11, 13, 14])

In [ ]:
a1


array([4, 7, 6, 8, 9])

In [ ]:
a2

array([4, 2, 7, 6, 3])

In [ ]:
a1+a2

array([ 8,  9, 13, 14, 12])

In [ ]:
a1 = np.array([3,5,4,6,7,9,3,1,2,6,7,9])
len(a1)

12

In [ ]:
a2 = a1.reshape(3,4)
a2

array([[3, 5, 4, 6],
       [7, 9, 3, 1],
       [2, 6, 7, 9]])

In [ ]:
a3 = np.array([2,4,6,8])
a3

array([2, 4, 6, 8])

In [ ]:
a2 + a3 # a3 will do add opefration on all rows

array([[ 5,  9, 10, 14],
       [ 9, 13,  9,  9],
       [ 4, 10, 13, 17]])

In [ ]:
a3 = a3.reshape(-1,1)
a3

array([[2],
       [4],
       [6],
       [8]])

In [ ]:
a1

array([3, 2, 6, 7, 8, 5, 4, 6])

In [ ]:
a1[[5,6,7]] # to extract values using index

array([5, 4, 6])

In [ ]:
# where aare the values which are greater than 4
# how mny values are greater than 4
# what are the values which are greater tham 4

-------------------------------------------------------------------
#input to the np.where command is the condition that to be chekcked
# op of np.where command is the indices where the condition is found to bee true

In [ ]:
ind = np.where(a1>4)
ind

(array([2, 3, 4, 5, 7]),)

In [ ]:
type(ind)

tuple

In [ ]:
len(ind) #Q1

1

In [ ]:
len(ind[0]) #Q1

5

In [ ]:
a1[ind[0]] #q3

array([6, 7, 8, 5, 6])

In [ ]:
(a1>4).sum() #SECOND QUE

np.int64(5)

In [ ]:
x1 = (np.arange(48)).reshape(6,8)   # creates a 2d array of 6 rows and 8 columns
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x2 = np.resize(x1,(12,4))   #  resizes the array x1 which was having 6 rows and 8 cols to an array with 12 rows and 4 cols
# are different items in a list. So basically we get list of arrays. By defaults axis=0 so splitting is done horizontally

x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [ ]:
x3 = np.split(x2,[1,3,5])	# splits the array at the indices mentioned. The resultant arrays
x3

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]])]

In [ ]:
x4 = np.split(x1,[2,3,5], axis=1)    # splitting happens vertically
x4

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25],
        [32, 33],
        [40, 41]]),
 array([[ 2],
        [10],
        [18],
        [26],
        [34],
        [42]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28],
        [35, 36],
        [43, 44]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31],
        [37, 38, 39],
        [45, 46, 47]])]

In [ ]:

b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])
c = sorted(b)          #sorts the array in increasing order
c

[np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [ ]:
c = sorted(b)[::-1]    # sorts the array in the decreasing order
c

[np.int64(9),
 np.int64(8),
 np.int64(7),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(4),
 np.int64(3),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(1)]

In [ ]:
np.sort(b)     # also PRINTS the array in the increasing order, original array is unchanged

array([1, 1, 2, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [ ]:
b=b.reshape(3,4)   # reshapes b as a 2d array with 3 rows and 4 columns
b

array([[2, 4, 1, 7],
       [6, 5, 9, 8],
       [2, 3, 1, 5]])

In [ ]:
np.sort(b,axis=0)   # row wise values will be changed. Column values are only rearranged

array([[2, 3, 1, 5],
       [2, 4, 1, 7],
       [6, 5, 9, 8]])

In [ ]:
np.sort(b,axis=1)   # column wise values will be changed. Row values are only rearranged

array([[1, 2, 4, 7],
       [5, 6, 8, 9],
       [1, 2, 3, 5]])

In [ ]:
ind = np.where(b>=4)
ind

(array([0, 0, 1, 1, 1, 1, 2]), array([1, 3, 0, 1, 2, 3, 3]))

In [ ]:
type(ind)

tuple

In [ ]:
len(ind)

2

array([[2, 4, 1, 7],
       [6, 5, 9, 8],
       [2, 3, 1, 5]])

In [ ]:
r1 = [5,8,3]


In [ ]:
r2 = r1*3

In [ ]:
r2

[5, 8, 3, 5, 8, 3, 5, 8, 3]

In [ ]:
a1 = np.array([2,6,5,4])


In [ ]:
a2 = np.repeat(a1, 3)
a2

array([2, 2, 2, 6, 6, 6, 5, 5, 5, 4, 4, 4])

In [ ]:
a2 = np.repeat(a1,([2,4,3,2]))
a2

array([2, 2, 6, 6, 6, 6, 5, 5, 5, 4, 4])

In [ ]:
a1 = np.array([4,7,6,1,3,8,7,2])

In [ ]:
np.argsort(a1) # will give indices of lowerst value to highest value

array([3, 7, 4, 0, 2, 1, 6, 5])

In [ ]:
a1[np.argsort(a1)]  #will retrn value

array([1, 2, 3, 4, 6, 7, 7, 8])

In [ ]:
a1 = np.array([6,5,4,8,7,6,2,2,5,7,1,7,1])

In [ ]:
len(a1)

13

In [ ]:
np.unique(a1)

array([1, 2, 4, 5, 6, 7, 8])

In [ ]:
np.unique(a1, return_counts= True)

(array([1, 2, 4, 5, 6, 7, 8]), array([2, 2, 1, 2, 2, 3, 1]))

In [ ]:
np.unique(a1, return_index= True) # where the number occured for first time

(array([1, 2, 4, 5, 6, 7, 8]), array([10,  6,  2,  1,  0,  4,  3]))

In [4]:
np.where(a1== 2)

(array([], dtype=int64),)

improvization : out of box

when there is OR in scenario probability will be added
when there is AND in scenario probability will be multiplied
for intersention OR
for union AND

**Day 2 19-05-2026**

In [3]:
a1 = np.array([3,7,6,1,8,9])
a2 = np.array([2,4,5,8,1,0,3,6])

In [6]:
np.intersect1d(a2, a2)

array([0, 1, 2, 3, 4, 5, 6, 8])

In [7]:
np.union1d(a1, a2)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.setdiff1d(a1, a2) # a2 elem are unique to a1

array([7, 9])

In [9]:
np.setxor1d(a1, a2)  # eithr only in a1 or a2 // union - intersection == xor gate

array([0, 2, 4, 5, 7, 9])

In [10]:
np.where(np.isin(a1,a2))

(array([0, 2, 3, 4]),)

In [11]:
x1 = np.array([2,3,-4])
x2 = np.array([3,-2,1])

In [12]:
np.dot(x1, x2)

np.int64(-4)

In [13]:
from numpy import linalg

In [15]:
x3 = np.array([[1,2,3,], [0,1,2],[1,1,0]])

In [16]:
np.linalg.det(x3)

np.float64(-1.0)

In [17]:
np.cross(x1, x2)

array([ -5, -14, -13])

In [19]:
from numpy import random

In [21]:
np.random.rand(10)

array([0.82377147, 0.77362994, 0.31556119, 0.78740373, 0.11084881,
       0.73862139, 0.87643506, 0.81058468, 0.23591345, 0.28148551])

In [24]:
np.random.randint(5, 15)

6

In [25]:
np.random.randint(5, 15, 5)

array([ 6,  6,  8, 12, 14])