In [ ]:
# 1 proportion test

In [ ]:
import numpy as np
import pandas as pd
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import scipy
from scipy import stats
from scipy.stats import binom, poisson, norm, t
from scipy.stats import expon

In [ ]:
binom.cdf(370,500,0.7) - binom.cdf(330,500,0.7)

np.float64(0.9488558323799914)

In [ ]:
from statsmodels.stats import proportion
proportion.proportions_ztest(100,400,0.4, alternative='larger')

(np.float64(-6.9282032302755105), np.float64(0.9999999999978689))

In [ ]:
import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

In [ ]:
# PUNE CDAC claiims that theyy have atleast 8% more engineers as compared to cdac mum
# h0 = pr(Pune0)-pr(mum) >=0.08  # HA = pr(Pune0)-pr(mum) < 0.08

In [ ]:
# 70 students 40 were btech in pune
# 80 students 48 were btech in mum

In [ ]:
40/70 - 48/80

-0.02857142857142858

In [ ]:
engg = np.array([40,48])


In [ ]:
total = np.array([70,80])

In [ ]:
statsmodels.stats.proportion.proportions_ztest(engg,total,0.08,alternative='smaller')

(np.float64(-1.3471563869719667), np.float64(0.08896493545619544))

In [ ]:
# claimed pattern for the qualification
# Btech  = 0.4, Mtech = 0.1, MCA = 45, MSC = 0.2
# BTech = 50, Mtech = 20, MCA = 45, MSC = 25
# whether counts obtain from sample follows the pattern or not

In [ ]:
counts = np.array([50,20,45,25])
pattern = np.array([0.4,0.1,0.3,0.2])

In [ ]:
exp_counts = sum(counts) * pattern
exp_counts

array([56., 14., 42., 28.])

In [ ]:
from scipy.stats import chisquare

In [ ]:
scipy.stats.chisquare(counts, f_exp = exp_counts) #not rejected

Power_divergenceResult(statistic=np.float64(11.614583333333334), pvalue=np.float64(0.008827096989130126))

In [ ]:
counts = np.array([70,10,35,45])
exp_counts = sum(counts) * pattern
exp_counts

array([64., 16., 48., 32.])

In [ ]:
scipy.stats.chisquare(counts, f_exp = exp_counts)
# p-value<0.05, so we reject Ho

Power_divergenceResult(statistic=np.float64(11.614583333333334), pvalue=np.float64(0.008827096989130126))

In [ ]:
sum((exp_counts - counts)**2/exp_counts)


np.float64(11.614583333333334)

In [ ]:
(exp_counts - counts)**2/exp_counts

array([0.5625    , 2.25      , 3.52083333, 5.28125   ])

In [ ]:
from scipy.stats import chi2_contingency

In [ ]:
# gender has any effect on choice category of food


In [ ]:
food = np.array([[45,70,60],[70,40,25]])
food

array([[45, 70, 60],
       [70, 40, 25]])

In [ ]:
scipy.stats.chi2_contingency(food)

Chi2ContingencyResult(statistic=np.float64(23.25424258416586), pvalue=np.float64(8.920832446902749e-06), dof=2, expected_freq=array([[64.91935484, 62.09677419, 47.98387097],
       [50.08064516, 47.90322581, 37.01612903]]))

In [ ]:
# DAY 13

In [ ]:
# a good class claims wold ask 20 ques per day
# H0 n>=20 Ha<20 ---->Left tail test

In [ ]:
question = [14,19,24,18,17,23,21,18,17]

In [ ]:
!pip install --upgrade statsmodels
from statsmodels.stats.rates import test_poisson_rate
test_poisson_rate(sum(question), len(question), 20, method='score', alternative='smaller')

ImportError: cannot import name 'test_poisson_rate' from 'statsmodels.stats.rates' (/usr/local/lib/python3.12/dist-packages/statsmodels/stats/rates.py)

In [ ]:
from statsmodels.stats.rates import test_poisson_2indep

ModuleNotFoundError: No module named 'statsmodel'

In [ ]:
# dbda natch asks atleast 6 que/day more than AI batch
# H0 avg couunt(dbda) - avg_count(ai) >=6
# H0 avg couunt(dbda) - avg_count(ai) < 6
# In dbda 12 days of training 145 ques werw asked
# in ai 5 days of training 45 ques were asked

In [ ]:
test_poisson_2indep(154,12,45,5, value=6, compare='diff', method='score', alternative='smaller')

NameError: name 'test_poisson_2indep' is not defined

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='faithful')

In [ ]:
erupt = df.eruptions

In [ ]:
np.var(erupt, ddof=1)

1.3027283328494672

In [ ]:
#H0 varience (erupt) <1.1
#H0 varience(erupt) <=1.1
#H0 varience (erupt) > 1.1 ---->right tail test
#TS = (N-1)*VARIENCE/(claim value)

In [ ]:
ts = (len(erupt)-1)*np.var(erupt, ddof=1)/1.1
ts

320.94488927473236

In [ ]:
p_value = 1-chi2.cdf(ts, len(erupt)-1)
p_value

np.float64(0.019972202957899476)

In [ ]:
from scipy.stats import chi2

In [ ]:
samp1 = erupt[30:70]
samp2 = erupt[130:180]

#H0 = var(samp1/var(samp2)) >= 1.4
#H0 = var(samp1/var(samp2)) < 1.4


In [ ]:
samp_ratio = np.var(samp1,ddof=1)/np.var(samp2,ddof=1)

In [ ]:
ts = samp_ratio/1.4

In [ ]:
from scipy.stats import f

In [ ]:
f.cdf(ts, len(samp1)-1, len(samp2)-1)

np.float64(0.32252763139863083)